### PR TITLE
use root project settings for compileSdkVersion, buildToolsVersion, etc 

### PR DESCRIPTION
**Pull request by maxmamis**

### CODE REVIEW

**Comment by maxmamis** [comment]
This allows the project to upgrade to a newer android SDK version (as required by React Native 0.5.6)

**Comment by ethanneff** [comment]
can confirm this works for latest version of React Native (0.56.0)

**Comment by MrHubble** [comment]
Is there anything stopping this from being merged into a new release?

**Comment by franck-nadeau** [comment]
I would like to confirm that this fix works. It would be nice for it to be merged in this project.

**Comment by annelorraineuy** [comment]
This package was updated recently. It would have been great if this PR was included.

**Comment by denisw** [comment]
The build is broken without this change:

```
Execution failed for task ':react-native-version-number:lint'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

  Errors found:

  /Users/dwas/Projects/Bosch/pro360.mobile.inventory-app/node_modules/react-native-version-number/android/build.gradle:10: Error: Google Play requires that apps target API level 26 or higher.
   [ExpiredTargetSdkVersion]
          targetSdkVersion 22
          ~~~~~~~~~~~~~~~~~~~
```

**Pull request merged**
