### PR TITLE
ensure RNVersionNumber exists for unit tests (with updated flow types)

### PR DESCRIPTION
**Pull request by vtsatskin**
This is based off of @evanjmg's work in #16. I've added flow type updates to reflect the potential void value.

### CODE REVIEW

**Comment by alvaromb** [comment]
Can you guys solve the conflicts?

@evanjmg I just made you collaborator, so feel free to merge this and ping me for the release 😉

**Comment by vtsatskin** [comment]
@alvaromb should be resolved now

**Comment by cvongrim** [comment]
Any chance of this getting merged in? Looks like the issues have been resolved.

**Comment by alvaromb** [comment]
https://github.com/APSL/react-native-version-number/releases/tag/v0.3.2

**Pull request merged**
